### PR TITLE
Panic when running s3 test

### LINKED ISSUE #110: Panic when running S3 test
How to reproduce:

```
$ $HOME/xk6-neofs/scenarios/preset/preset_s3.py --endpoint 192.168.43.84:7130 --preload_obj 2 --buckets 2 --size 4 --out $HOME/xk6-neofs/2obj_4kb_2b.json
Namespace(size='4', buckets='2', out='/home/ansible/xk6-neofs/2obj_4kb_2b.json', preload_obj='2', endpoint='192.168.43.84:7130', update=None, location='', versioning=None, workers=50)
Create buckets: 2
cmd: aws --no-verify-ssl s3api create-bucket --bucket e95dd5c9-5789-4ba3-97e5-86a0b1df59fc --endpoint http://192.168.43.84:7130 
cmd: aws --no-verify-ssl s3api create-bucket --bucket 0cea9f7d-15f4-4eaa-9b01-a0a3b7a2f6d6 --endpoint http://192.168.43.84:7130 
Create buckets: Completed
 > Buckets: ['e95dd5c9-5789-4ba3-97e5-86a0b1df59fc', '0cea9f7d-15f4-4eaa-9b01-a0a3b7a2f6d6']
Upload objects to each bucket: 2 
 > Create random payload: Completed
 > Upload objects for bucket e95dd5c9-5789-4ba3-97e5-86a0b1df59fc
 > Upload objects for bucket e95dd5c9-5789-4ba3-97e5-86a0b1df59fc: Completed
 > Upload objects for bucket 0cea9f7d-15f4-4eaa-9b01-a0a3b7a2f6d6
 > Upload objects for bucket 0cea9f7d-15f4-4eaa-9b01-a0a3b7a2f6d6: Completed
Upload objects to each bucket: Completed
Result:
 > Total Buckets has been created: 2.
 > Total Objects has been created: 4.
$ $HOME/xk6-neofs/xk6-neofs run $HOME/xk6-neofs/scenarios/s3.js -e S3_ENDPOINTS=192.168.43.84:7130,192.168.43.85:7130,192.168.43.86:7130,192.168.43.87:7130 -e PREGEN_JSON=$HOME/xk6-neofs/2obj_4kb_2b.json -e DURATION=30 -e READERS=1

         /\      Grafana   /‾‾/  
    /\  /  \     |\  __   /  /   
   /  \/    \    | |/ /  /   ‾‾\ 
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/ 

     execution: local
        script: /home/ansible/xk6-neofs/scenarios/s3.js
        output: -

     scenarios: (100.00%) 1 scenario, 1 max VUs, 35s max duration (incl. graceful stop):
              * read: 1 looping VUs for 30s (exec: obj_read, gracefulStop: 5s)

INFO[0000] Pregenerated buckets:          2              source=console
INFO[0000] Pregenerated read object size: 4 Kb           source=console
INFO[0000] Pregenerated total objects:    4              source=console
INFO[0000] Reading VUs:                   1              source=console
INFO[0000] Writing VUs:                   0              source=console
INFO[0000] Deleting VUs:                  0              source=console
INFO[0000] Total VUs:                     1              source=console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa12dd7]
read   [--------------------------------------] 1 VUs  00.2s/30s
goroutine 43 [running]:
github.com/mstoykov/atlas.(*Node).ValueByKey(0x21cf520?, {0x258e6dd?, 0x80?})
	/home/ansible/go/pkg/mod/github.com/mstoykov/atlas@v0.0.0-20220811071828-388f114305dd/atlas.go:45 +0x17
go.k6.io/k6/metrics.(*TagSet).Get(...)
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/metrics/tags.go:58
go.k6.io/k6/internal/output/summary.(*Output).storeSample(0xc0000a6c00, {{0xc0005bbc20, 0x0}, {0xc238a9b7e46968cf, 0x2e9153d, 0x3e67720}, 0x3ff0000000000000, 0x0})
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/internal/output/summary/summary.go:177 +0x34a
go.k6.io/k6/internal/output/summary.(*Output).flushSample(0xc0000a6c00, {{0xc0005bbc20, 0x0}, {0xc238a9b7e46968cf, 0x2e9153d, 0x3e67720}, 0x3ff0000000000000, 0x0})
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/internal/output/summary/summary.go:86 +0x78
go.k6.io/k6/internal/output/summary.(*Output).flushMetrics(0xc0000a6c00)
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/internal/output/summary/summary.go:79 +0xd2
go.k6.io/k6/output.(*PeriodicFlusher).run(0xc000594990)
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/output/helpers.go:69 +0x6b
created by go.k6.io/k6/output.NewPeriodicFlusher in goroutine 1
	/home/ansible/go/pkg/mod/go.k6.io/k6@v1.3.0/output/helpers.go:102 +0x11a
```

### PR DESCRIPTION
**Pull request by smallhive**
Closes #110

### CODE REVIEW

File: internal/native/client.go [hunk 1]
```diff
@@ -404,15 +403,13 @@ func (c *Client) Onsite(containerID string, payload sobek.ArrayBuffer) PreparedO
...
-	obj.SetOwnerID(&c.owner)
+	obj.SetOwner(c.owner)
 	obj.SetPayloadSize(uint64(ln))
 	obj.SetCreationEpoch(epoch)
 
 	var sha, hh checksum.Checksum
-	sha.SetSHA256(sha256.Sum256(data))
 	obj.SetPayloadChecksum(sha)
 	if !hhDisabled {
-		hh.SetTillichZemor(tz.Sum(data))
```
Comment (carpawell) [inline internal/native/client.go]: why it sets zero hashes now?

**Review by roman-khimov — APPROVED** [review]
